server:
  port: 9999
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=QLCongVan;integratedSecurity=false
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
file.upload-dir: D:\saveCongVan
security-auth:
  enabled: false
logging:
  level:
    root:
